[package]
name = "coblox_bitcoincore"
version = "0.1.0"
authors = [
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Franck Royer <franck@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>",
]
description = "Testcontainers image for the coblox/bitcoin-core docker image."
license = "MIT OR Apache-2.0"
repository = "https://github.com/coblox/testcontainers-rs"
categories = ["development-tools::testing"]
keywords = ["docker", "testcontainers", "bitcoin"]

[badges]
travis-ci = { repository = "coblox/testcontainers-rs" }

[dependencies]
testcontainers = { path = "../../testcontainers", version = "0.1.0" }
log = "0.4.3"
hmac = "0.5"
sha2 = "0.7"
hex = "0.3.2"
rand = "0.5.4"

[dev-dependencies]
bitcoin_rpc = { git = "ssh://git@github.com/coblox/bitcoincore-rpc_rust_client.git", branch = "prepare-for-open-source" }
