language: rust
sudo: required
addons:
  apt:
    packages:
    - libssl-dev
cache:
  directories:
  - "$HOME/.cargo"
  - "$HOME/.cache/sccache"
rust: stable
services:
  - docker
before_script:
- docker pull coblox/bitcoin-core:0.17.0
- docker pull trufflesuite/ganache-cli:v6.1.3
- docker pull parity/parity:v1.11.11
- docker pull postgres:9.6-alpine
- rustup component add rustfmt
- which sccache || cargo install sccache
script:
- cargo fmt -- --check
- RUSTC_WRAPPER=~/.cargo/bin/sccache cargo build --all --all-targets
- RUSTC_WRAPPER=~/.cargo/bin/sccache cargo test --all
