language: rust
rust: stable
cache: cargo
sudo: required
addons:
  apt:
    packages:
    - libssl-dev
services:
  - docker
before_script:
- rustup component add rustfmt
- which sccache || cargo install sccache
script:
- cargo fmt -- --check
- RUSTC_WRAPPER=~/.cargo/bin/sccache cargo build --all --all-targets
- RUSTC_WRAPPER=~/.cargo/bin/sccache cargo test --all
