[package]
name = "testcontainers"
version = "0.2.0"
authors = [
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Franck Royer <franck@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>",
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/coblox/testcontainers-rs"
categories = ["development-tools::testing"]
keywords = ["docker", "testcontainers"]
description = "A library for integration-testing against docker containers from within Rust."

[dependencies]
serde = "1.0.66"
serde_json = "1.0.22"
serde_derive = "1.0.66"
log = "0.4.3"
